version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      electron-toolchain:
        patterns:
          - electron
          - electron-builder
      dev-dependencies:
        dependency-type: development
        exclude-patterns:
          - electron
          - electron-builder
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
